apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: ahmed-event-booking  # Replace with your actual name
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: event-booking-user-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3001"
            - name: DB_PATH
              value: "/app/data/user.sqlite"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jwt-secret
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: rabbitmq-url
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          volumeMounts:
            - name: user-data
              mountPath: /app/data
      volumes:
        - name: user-data
          persistentVolumeClaim:
            claimName: user-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: OnlineEventBookingYourName  # Replace with your actual name
spec:
  selector:
    app: user-service
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-data-pvc
  namespace: OnlineEventBookingYourName  # Replace with your actual name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi