apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: OnlineEventBookingAhmed  # Replace with your actual name
type: Opaque
data:
  # These are base64 encoded values - for production, use proper secrets management
  mongodb-password: cGFzc3dvcmQ=  # 'password' encoded
  rabbitmq-password: cGFzc3dvcmQ=  # 'password' encoded
  jwt-secret: c3VwZXJfc2VjcmV0X2p3dF9rZXk=  # 'super_secret_jwt_key' encoded